apiVersion: v1
kind: Pod
metadata:
  name: dev-brocker
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
            - arm64
  containers:
  - name: single-broker
    image: medinvention/kafka:2.13-2.7.0
    env:
    - name: HOSTNAME_VALUE
      value: "127.0.0.1"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "zk-cs.kafka.svc.cluster.local:2181"
    - name: KAFKA_LOG4J_OPTS
      value: "-Dlog4j.configuration=file:/opt/kafka/config/log4j.properties"
    - name: KAFAK_AUTO_CREATE_TOPICS_ENABLE
      value: "false"
    ports:
    - containerPort: 9092
    volumeMounts:
    - name: data
      mountPath: /var/lib/kafka/data
  volumes:
  - name: data
    emptyDir: {}