apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-broker
  replicas: 2
  template:
    metadata:
      labels:
        app: kafka
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: broker
        image: medinvention/kafka:2.13-2.7.0
        env:
        - name: HOSTNAME_COMMAND
          value: "echo \"${HOSTNAME}.kafka-broker.kafka.svc.cluster.local\""
        - name: KAFKA_LISTENERS
          value: "SSL://_{HOSTNAME_COMMAND}:9093"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "SSL"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "SSL://_{HOSTNAME_COMMAND}:9093"
        - name: KAFKA_SSL_KEYSTORE_LOCATION
          value: "/var/lib/kafka/ssl/kafka.keystore.jks"
        - name: KAFKA_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ssl
              key: keystore_password
        - name: KAFKA_SSL_KEY_PASSWORD
          value: "passcode"
        - name: KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
          value: ""
        - name: KAFKA_SSL_TRUSTSTORE_LOCATION
          value: "/var/lib/kafka/ssl/kafka.truststore.jks"
        - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ssl
              key: truststore_password
        - name: KAFKA_SSL_ENABLED_PROTOCOLS
          value: "TLSv1.2,TLSv1.1,TLSv1"
        - name: KAFKA_LOG4J_OPTS
          value: "-Dlog4j.configuration=file:/opt/kafka/config/log4j.properties -Djava.security.auth.login.config=/var/lib/kafka/jass/jaas.conf"
        - name: BROKER_ID_COMMAND
          value: "echo ${HOSTNAME##*-}"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zk-cs.kafka.svc.cluster.local:2181"
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/kafka/data/topics"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "-1"
        - name: KAFAK_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "6000"
        - name: KAFAK_AUTO_CREATE_TOPICS_ENABLE
          value: "false"
        ports:
        - containerPort: 9093
        livenessProbe:
          initialDelaySeconds: 60
          exec:
            command:
            - /bin/sh
            - -c
            - 'netstat -tulpn | grep LISTEN | grep 9093'
        volumeMounts:
        - name: data
          mountPath: /var/lib/kafka/data
        - name: ssl
          mountPath: /var/lib/kafka/ssl
          readOnly: true
        - name: jaas
          mountPath: /var/lib/kafka/jass
          readOnly: true
      volumes:
      - name: ssl
        secret:
          secretName: ssl
          items:
            - key: kafka.keystore.jks
              path: kafka.keystore.jks
            - key: kafka.truststore.jks
              path: kafka.truststore.jks
      - name: jaas
        secret:
          secretName: kafka-jaas
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi